### PR TITLE
Add a paste results option

### PR DESCRIPTION
**Pull request by liamdawson**
Record all displayed results since the last run, and add a menu option to paste these results at the cursor.

I am experiencing an issue with this code though - if I run the `colors.py` example and paste into an new document, it works fine. If I then go and paste into the document I just ran, Atom locks up. I've never worked with atom internals before though, so I'm unsure where to look.

### CODE REVIEW

**Comment by liamdawson** [comment]
I also did not add a default keymap entry as my first choice, ctrl-alt-v, is a default shortcut in Evernote, which I had been completely unaware of.

**Comment by erran** [comment]
> I am experiencing an issue with this code though - if I run the colors.py example and paste into an new document, it works fine. If I then go and paste into the document I just ran, Atom locks up.

Due to the nature of that issue, and the fact that I had to either wait for Atom to detect the unresponsive window/force quit the application, I'd be uncomfortable merging this.

@liamdawson what do you think about adding a "Copy Results" function instead? You could use `atom.clipboard.write results` to [write to the clipboard](https://atom.io/docs/api/v0.176.0/Clipboard) instead.

**Comment by erran** [comment]
> You could use atom.clipboard.write results to write to the clipboard instead.

After testing this I realized that the issue is actually a limitation in pasting text with atom. If you manually copy and paste the color.py output the text is escaped and doesn't cause Atom to hang. I'll look into this more.

**Comment by erran** [comment]
@liamdawson I'd prefer a `Copy Results` command since writing immediately could have consequences. I've successfully pasted longer output which can be slower but never hung completely for me (I pasted up to ~10k lines).

@rgbkrk What do you think?

Also make sure you add notes to the README.

**Comment by rgbkrk** [comment]
Breaking it up to be about copy first and foremost makes sense to me. Making utilities on top of that sounds like grounds for working with an event model that another plugin can use itself.

**Comment by liamdawson** [comment]
I'll convert it into a copy results option when I get home. Is there any way to avoid the Atom pasting issue, or do we just have to wait for a fix in Atom itself?

Any suggestions for a default keybinding?

**Comment by liamdawson** [comment]
Now changed the command to "Copy Run Results", which then copies the run results to the clipboard. Added an entry to the `README.md` about it. No default keybinding. Also, the Python examples tend to be a bit Python 3 unfriendly.

**Comment by rgbkrk** [comment]
I'm certainly open to Python 3 compatible changes to the examples. I'm using Python 3 exclusively now myself.

**Comment by erran** [comment]
The only thing that's keeping me from merging this now is the fact that using copy results will include any ANSI color escapes which isn't what I'd expect to be in my clipboard. I'll look into escaping this and add more feedback in a bit.

**Comment by liamdawson** [comment]
Merged pull request by @erran.

**Comment by rgbkrk** [comment]
:+1:

**Pull request merged**
