### PR TITLE
Address Atom deprecations

### LINKED ISSUE #266: Atom.Object.defineProperty.get is deprecated.
atom.workspaceView is no longer available.
In most cases you will not need the view. See the Workspace docs for
alternatives: https://atom.io/docs/api/latest/Workspace.
If you do need the view, please use `atom.views.getView(atom.workspace)`,
which returns an HTMLElement.
```
Atom.Object.defineProperty.get (/Applications/Atom.app/Contents/Resources/app/src/atom.js:55:11)
ScriptView.initialize (/Users/innafinit/.atom/packages/script/lib/script-view.coffee:28:9)
```

### PR DESCRIPTION
**Pull request by erran**
This PR should be thoroughly tested. I haven't fully tested it. The deprecation warnings are gone but I haven't tested each variation of the commands they affect. For example the subscriptions API has changed and we should also refactor the way we trigger events to use disposables.

Fixes #266.

### CODE REVIEW

**Comment by rgbkrk** [comment]
Thank you so much @erran!

**Comment by erran** [comment]
> Thank you so much @erran!

No problem, I had some time today. I closed several dups of the deprecation issues today. I've rebased and pushed the minimum to remove the deprecations. Merge after you get some time to test it (I've already done so).

**Comment by rgbkrk** [comment]
I'm on a chromebook for the weekend so I won't be able to test it out any time soon. (My Mac died)

**Comment by rgbkrk** [comment]
I went ahead and gave this branch for a spin, it needed a minor rebase for the `copyResults`. Locally I did it by adding

```coffeescript
atom.commands.add 'atom-workspace', 'script:copy-run-results', => @copyResults()
```

**Pull request closed without merging**
