### PR TITLE
Add Java grammar.

### PR DESCRIPTION
**Pull request by pardom**
File-based Java scripts only for now. Selection-based scripts would
require naming the temp file to match the main class, and also finding
the main class in the selection. This could be done by passing in a file
name and searching for the first instance of `/class (.*)\{/`, but I don't
feel comfortable doing this without significant testing and suggestions
for the current contributors.

### CODE REVIEW

**Comment by rgbkrk** [comment]
The only issue is that `bash` isn't necessarily cross platform. Can you report a useful error message on Windows? With the way our current `command` gets passed over, you'll likely need to add in something a bit more. Would help for other compiled languages that don't have a "run single file" option either.

**Comment by rgbkrk** [comment]
Also, thank you for having at it!

**Comment by rgbkrk** [comment]
```
$ apm publish minor
Preparing and tagging a new version ✓
Pushing v2.24.0 tag ✓
Publishing script@v2.24.0 ✓
```

**Comment by rgbkrk** [comment]
I'm adding you on as a maintainer to help with the Java and related languages @pardom. Thank you so much!

**Comment by EntilZha** [comment]
Seems like I got added as a maintainer. While I don't mind it, not sure if it was intended since although I contributed to this a while ago (and use it from time to time), I don't know the code base anymore at all.

**Comment by pardom** [comment]
Nice, thanks. :+1:

**Comment by rgbkrk** [comment]
Ah yeah I added you because you contributed quite a bit @entilzha.

**Comment by rgbkrk** [comment]
Sorry I meant to message you as well,

**Comment by EntilZha** [comment]
No problem @rgbkrk, just wanted to make sure. I have been using Atom quite a bit as of a few months ago so perhaps there is something I find I want to work on. Mostly I am using PyCharm/IntelliJ for more intensive coding, Vim for fast file edit/viewing, and Atom for everything in between.

**Comment by rgbkrk** [comment]
Oh hey, that's pretty neat.

**Pull request merged**
