### PR TITLE
Fix coffee error message

### PR DESCRIPTION
**Pull request by nixel2007**
As was mentioned [here](https://github.com/rgbkrk/atom-script/issues/789#issuecomment-185740854)

### CODE REVIEW

**Comment by rgbkrk** [comment]
Whoa, you can drop a catch?

**Comment by rgbkrk** [comment]
I haven't been a fan of this coffee setup for a while, since it keeps breaking things for folks. Probably need to think on what it's trying to do again.

**Comment by nixel2007** [comment]
@rgbkrk 
> Whoa, you can drop a catch?

no errors on my machine (no coffee installed)

**Comment by nixel2007** [comment]
> I haven't been a fan of this coffee setup for a while, since it keeps breaking things for folks. Probably need to think on what it's trying to do again.

looks like it tries to determinate some type of cofee setup/interpreter and push an additional arg. Don't know if we need it ever.

**Pull request merged**
