### PR TITLE
Update to the Nim/NimScript runner

### PR DESCRIPTION
**Pull request by oderwat**
- Added Nim/NimScript support to readme
- Made runner using cd and short filename to better support how Nim works with relative paths in config file.

P.S.: Please create a new atom-package. The NimScript version is not yet available it seems.

### CODE REVIEW

**Comment by rgbkrk** [comment]
Want to try your hand at shipping this?

**Comment by oderwat** [comment]
You mean creating a release pack? I do not have an idea how to do that.

**Comment by rgbkrk** [comment]
Yeah, that's ok though. As I noted in #569, it seems like we're not ready for the release just yet.

**Comment by rgbkrk** [comment]
Generally though, [publishing a package](https://atom.io/docs/v0.74.0/publishing-a-package) is a matter of:

* Picking whether this is a major, minor, or patch release. (This is going to end up being a major release)
* Updating the CHANGELOG with what happened since last release (look at the list of commits, then you can form a URL like: https://github.com/rgbkrk/atom-script/compare/27d1f915e5a3c5eb3dd412696aa2819683cc580b...master).
* Running `apm publish major` (or whatever variant)

**Comment by oderwat** [comment]
Well OK. I also noticed delays in the "console" output which was my biggest concern in moving away from my beloved "CodeRunner" :) I would also love to see real-time memory usage of whats running btw. Still I have many other things to do and was looking into script because the Nim Lang package did not come with an inline terminal like I love since using CodeRunner for smaller projects and tests.

**Pull request merged**
