### PR TITLE
The grand refactoring along with exposing two services to run code from other packages

### PR DESCRIPTION
**Pull request by s1mplex**
Hey @rgbkrk ! This got quite big but hopefully you'll find it worth it. 

I wanted to be able to customize code running so I can provide an input, write output somewhere else etc. I believe the good way to go is to expose a service - this way the script package remains unchanged while we can develop other packages around it. A good use case would be to imagine a Google Code Jam package that'd use atom-script: you'd choose the challenge, the package would run your code locally against the automatically downloaded input and submit your output back to Google.

I wanted to do it the right way so I did a lot of refactoring. I pulled responsibilities out of the `ScriptView` class into a few more of them:

* **Runner** that encapsulates running behaviour
* **CodeContextBuilder** which builds CodeContext for Runner
* **CommandContext** which was previously a plain object
* **Runtime** which pulls it all together and can emit events connected with the running lifecycle to observers
* **ViewRuntimeObserver** which listens to Runtime and calls ScriptView

I also added a few tests to make sure the basic functionality is there.

Let me know what you think! Just to let you know - I'll be on vacation for two weeks so I might not be very quick with my responses in that time.

### CODE REVIEW

**Comment by s1mplex** [comment]
@rgbkrk any thoughts here?

**Comment by rgbkrk** [comment]
oh whoa, new stuff. Didn't realize you had rebased and added on. I'll have to take a look.

**Comment by rgbkrk** [comment]
Glad you added several new specs here certainly as well as using Atom's Emitter.

**Comment by rgbkrk** [comment]
Gah, I was going to try this out and possibly ship it. This needs a rebase but I can still review it.

**Comment by s1mplex** [comment]
@rgbkrk I'll rebase it in the next few days

**Comment by s1mplex** [comment]
@rgbkrk I've just rebased it on top of master. Let me know if you encounter any problems!

**Comment by rgbkrk** [comment]
Adding you on as a maintainer @s1mplex, thanks for this.

**Comment by rgbkrk** [comment]
This has certainly cleaned up the UI and a bunch of the code, but I'm noticing that it waits to be finished before showing anything from stdout. Example Python

```python
import time

print("hey")
for ii in range(2):
    print(ii)
    time.sleep(1)
```

Not until after it's over will you see any output (all sleeping finished).

**Comment by rgbkrk** [comment]
I'm now realizing I can't ship this as it doesn't give feedback like a terminal would.

**Comment by s1mplex** [comment]
@rgbkrk I'll take a look at it

**Comment by rgbkrk** [comment]
Any word? I'm going to ship this and see how people handle it.

**Comment by s1mplex** [comment]
I have it in my to-do but I'm having hard time with finding a bit of spare
time ATM :/

niedz., 18.10.2015 o 05:57 użytkownik Kyle Kelley <notifications@github.com>
napisał:

**Pull request merged**
