### PR TITLE
added Prolog with swipl

### LINKED ISSUE #775: Add support for Prolog

### PR DESCRIPTION
**Pull request by Chosko**
Fixes #775

### CODE REVIEW

**Comment by rgbkrk** [comment]
Changes look good, I'm not sure why one of the entries in the build matrix is failing.

**Comment by rgbkrk** [comment]
Are tests passing locally for you? They are on my machine. I don't think this test should hold up your current PR.

Thanks for the contribution, I'm adding you on as a maintainer to help us along.

**Comment by Chosko** [comment]
Tests are passing on my machine too... What's the entry that is failing in the build matrix?

Thanks for adding me as a mantainer!

**Comment by Chosko** [comment]
I see the failing entry. It's weird, after the pull request was merged the build succeded.

**Pull request merged**
