### PR TITLE
Feature/add cpp14

### PR DESCRIPTION
**Pull request by erip**
Here are some changes that address #966. 

Take it or leave it, but it seems to work for me. 😏

### CODE REVIEW

**Comment by nixel2007** [comment]
does it break the c-11 support?

**Comment by erip** [comment]
It replaces it.

**Comment by erip** [comment]
Although in the original grammar, there was no explicit handling of C++11.

Code compiled on Darwin added C++11 extensions, while all other platforms compiled without specifying a standard version.

**Comment by rgbkrk** [comment]
Bringing it in. Thanks @erip. Adding you on as a maintainer while we keep evolving.

**Comment by nixel2007** [comment]
:ship: 3.11.1

**Pull request merged**
