### PR TITLE
Restyled options view, fixes #213 issue

### LINKED ISSUE #213: Broken styling in ScriptOptionsView
Using v2.11.2 I see the following style in the script options view.
screen shot 2014-10-16 at 14 49 18

### PR DESCRIPTION
**Pull request by Stormherz**
I've refactored and restyled run options view a bit, it will fix #213. Few screenshots in dark/light themes attached.

script_options_1
script_options_2

### CODE REVIEW

**Comment by rgbkrk** [comment]
Awesome!

**Comment by rgbkrk** [comment]
Would you enjoy shipping it too?

**Comment by Stormherz** [comment]
Sure, but first I need to know what shipping is, in terms of github =) I got a few guesses - deployment, release preparation? Some kind of pirates activity..?

**Comment by rgbkrk** [comment]
We gather in a circle chanting `script script script`.

Then we go back to our terminals, make sure we have the latest from master (assuming `origin` is this remote and that you have it set to `git@github.com:rgbkrk/atom-script.git`):

```
git checkout master
git pull origin/master
apm publish patch
```

I've not looked at the last few commits to tell if this is a patch or minor release though. You tell me and we'll coordinate from there. Happy to do a video chat too.

**Comment by nixel2007** [comment]
looks really awesome! love it!

**Comment by Stormherz** [comment]
@nixel2007 thanks!
@rgbkrk ah, I see =) I'll publish today then, within next 5-6 hours after last commits check - what do we usually consider as a minor release? Changes in logic, new languages support, etc? As for current changes - I guess that's a patch for sure, not that big even for minor release. Video chat would be helpful if English was my first language =)

**Comment by rgbkrk** [comment]
Ah, that's ok. Thanks for patience with me in offering the video chat. I just want to make things easy.

With node packages I have a really easy idea of what Semver means, since it's about exposed interfaces. For UI like these Atom plugins, I'm really not sure. It's like a sliding scale on UI changes. I'd love to hear someone's opinion on this.

This one is likely just a patch release, though it does change the interface for the user a bit.

**Comment by Stormherz** [comment]
Not a brand new shiny, smart idea, but - maybe we should decide basing on average number of issues, related to specific changes? E.g. this changes in options view is related to #213 only (though I didn't check other issues thoroughly) without additional users asking for it - so it's considered a patch. If #213 had hundreds of people, crying in frustration and suffering - changes would be considered as release.

However, come to think of it, that's not really a reliable way of marking shippings - not all of the users are patient enough to leave note in issues, and most of the time they will just say "meh" and remove the plugin they didn't like for some reason.

**Comment by rgbkrk** [comment]
I think it's alright to call this one a patch, go for it.

**Comment by Stormherz** [comment]
Aaaand it's gone. Sorry for taking your time to clarify the process, I'm quite new with apm. Next time it won't take any additional time =)

**Comment by rgbkrk** [comment]
Thank you and no problem!

**Pull request merged**
