### PR TITLE
added 'latexmk' based build for LaTeX documents

### PR DESCRIPTION
**Pull request by MrAdam**

### CODE REVIEW

**Comment by rgbkrk** [comment]
Can you also add this to the README?

Closes #154 and #555. What do you think @MaruPr, @karloluis, @Alghamdi, @andya9, @pandres95?

**Comment by pandres95** [comment]
:+1: :smile:

**Comment by MrAdam** [comment]
I will add it to Readme tomorrow.
I should note though, that this only works if people have latexmk installed, which is not included in all LaTeX distributions.
The problem with getting it to work without latexmk is that you would have to run a series of commands, which differs in different situations. latexmk handles calling the correct commands, which is why I think it's better to just add support for that.

**Comment by MrAdam** [comment]
Added preview to command, and entry in readme

**Comment by andya9** [comment]
Thank’you very much @MrAdam !

**Comment by rgbkrk** [comment]
I'll ship a release later today.

**Comment by andya9** [comment]
Thank’you too @rgbkrk !

**Comment by rgbkrk** [comment]
Oh how delightful.

```
$ npm install

> script@2.26.4 prepublish /Users/kyle6475/code/src/atom.io/packages/script
> node utils/updatePackage.js

Segmentation fault: 11
$ apm install
Installing modules ✗
> script@2.26.4 prepublish /Users/kyle6475/code/src/atom.io/packages/script
> node utils/updatePackage.js


dyld: lazy symbol binding failed: Symbol not found: _node_module_register
  Referenced from: /Users/kyle6475/code/src/atom.io/packages/script/node_modules/nodegit/build/Release/nodegit.node
  Expected in: flat namespace

dyld: Symbol not found: _node_module_register
  Referenced from: /Users/kyle6475/code/src/atom.io/packages/script/node_modules/nodegit/build/Release/nodegit.node
  Expected in: flat namespace
```

**Comment by rgbkrk** [comment]
Nuked node_modules, I definitely did an upgrade that wasn't compatible with nodegit (used for creating the CHANGELOG).

**Comment by rgbkrk** [comment]
Thanks again for this @MrAdam, I've finally shipped this. In addition, I've added you as a collaborator so you can help maintain this part of the code as well as any other pieces you'd like to help with.

:tada:

**Comment by MrAdam** [comment]
Thank you @rgbkrk, I'll try and keep this updated, and look into any bugs reported for LaTeX :+1:

**Pull request merged**
