### PR TITLE
Adds the extraPathEntries config setting

### PR DESCRIPTION
**Pull request by andrenpaes**
This allows users to add extra directories to the PATH environment variable used to run scripts.

Demo:
atom-script

### CODE REVIEW

**Comment by rgbkrk** [comment]
This should probably accept extra path entries as containing path delimeters. Then it's right in kind with normal shell tools and the Windows Path setup.

**Comment by rgbkrk** [comment]
Thanks for taking a crack at this!

**Comment by andrenpaes** [comment]
The original idea is for this to work as list of locations to be added to the PATH. It's leveraging Atom's built-in conversion based on the config JSON schema (which converts a comma separated string into an array automatically).

The main advantage of this approach is that, for the end user, the intent is pretty clear, it extends the PATH. You don't have to worry if it actually overwrites the PATH, or which separator should you be using (: for *nix and ; for windows).

We can go the way you're suggesting, but the in that case, type in the config schema changes to just string.

**Comment by rgbkrk** [comment]
Care to rebase and we'll discuss again?

**Comment by rgbkrk** [comment]
Closing since I haven't heard anything back in a while.

**Pull request closed without merging**
