### PR TITLE
Add Support for Crystal (www.crystal-lang.org)

### PR DESCRIPTION
**Pull request by MichaelSp**

### CODE REVIEW

**Comment by rgbkrk** [comment]
Looks good. I assume you're using https://github.com/k2b6s9j/language-crystal for the syntax highlighting?

**Comment by MichaelSp** [comment]
Yes, That's right.

**Comment by k2b6s9j** [comment]
:grinning:

**Comment by k2b6s9j** [comment]
@bcardiff, check it out! More Crystal IDE in Atom stuff!

**Pull request merged**
