### PR TITLE
Support Stata. Fix #121

### LINKED ISSUE #121: [Push request]: add "do" language -for Stata- (here is the code)
I edited the file <code>grammars.coffee</code> with this:
```coffee
  do:
    "Selection Based":
      command: "xstata-se"
      args: (code)  -> [' do ', code]
    "File Based":
      command: "xstata-se"
      args: (filename) -> [' do ',filename]
```
that allows Atom to run stata <code>.do</code> files. The language definitions are in my repo http://git.io/gkctpQ.

### PR DESCRIPTION
**Pull request by nixel2007**
Support Stata language.
Fix #121 

@nickeubank please check this, if you can.

### CODE REVIEW

**Comment by rgbkrk** [comment]
Ready to merge in the next couple days if we don't hear back from @nickeubank.

**Comment by nixel2007** [comment]
Looks like I forgot to add a Readme entry. 

Отправлено с моего HTC

----- Ответное сообщение -----
От: "Kyle Kelley" <notifications@github.com>
Кому: "rgbkrk/atom-script" <atom-script@noreply.github.com>
Копия: "Nikita Gryzlov" <nixel2007@gmail.com>, "Author" <author@noreply.github.com>
Тема: [rgbkrk/atom-script] Support Stata. Fix #121 (#940)
Дата: вт, мая 24, 2016 04:16

Ready to merge in the next couple days if we don't hear back from @nickeubank.

&mdash;You are receiving this because you authored the thread.Reply to this email directly or view it on GitHub

**Comment by nickeubank** [comment]
Thanks @nixel2007 ! I think the problem is going to be there are a [lot of flavors of Stata](http://www.statanordic.com/stataflavors.html), and that look specific to one version (stata-se). Would it be hard to make the command-line invocation of stata easily settable by the user?

**Comment by nixel2007** [comment]
@nickeubank you can override the comand in script settings view and/or in profile. 

but we need to set the most commonly used version of stata runner to set it as default. is `se`-version suitable for this?

**Comment by nickeubank** [comment]
Probably? Honestly I'm not sure relative market shares. It's a reasonable choice for a default to be sure.

**Comment by rgbkrk** [comment]
We'll go with reasonable and let new PRs flow in.

**Comment by rgbkrk** [comment]
Want to ship it @nixel2007?

Thanks for making the change.

**Comment by nixel2007** [comment]
@rgbkrk sure. give me a minute

**Comment by nickeubank** [comment]
@nixel2007 Thanks!

**Comment by nixel2007** [comment]
:ship:

**Comment by spheres-sumrain** [comment]
Thanks for the fix! The "File Based" push works fine. However, for the "Selection Based" push, xstata expects no `'do'` command in front of the code, but simply the sequence of Stata commands (i.e. the code).

Removing the `'do',` part in the "Selection Based" push then highlights another problem: the selection of code that atom-script sends to xstata is received as a single line of code, although every line of code should be sent as a separate line to xstata. Does anybody know how to fix this?

**Pull request merged**
