### PR TITLE
Remove wrong function call

### LINKED ISSUE #847: Deactivation throws error
This string raise an error in console when try to deactivate or update package - https://github.com/rgbkrk/atom-script/blob/master/lib/script-profile-run-view.coffee#L128

```
Error deactivating package 'script' ReferenceError: toggleProfileRun is not defined
    at ScriptProfileRunView.module.exports.ScriptProfileRunView.close (file:///C:/Users/na_gryzlov/.atom/packages/script/lib/script-profile-run-view.coffee:128:5)
    at Object.module.exports.deactivate (file:///C:/Users/na_gryzlov/.atom/packages/script/lib/script.coffee:116:27)
    at Package.module.exports.Package.deactivate (C:\Users\na_gryzlov\AppData\Local\atom\app-1.5.4\resources\app.asar\src\package.js:646:21)
    at PackageManager.module.exports.PackageManager.deactivatePackage (C:\Users\na_gryzlov\AppData\Local\atom\app-1.5.4\resources\app.asar\src\package-manager.js:595:12)
    at C:\Users\na_gryzlov\AppData\Local\atom\app-1.5.4\resources\app.asar\src\package-manager.js:333:21
    at C:\Users\na_gryzlov\AppData\Local\atom\app-1.5.4\resources\app.asar\src\config.js:631:20
    at Function.module.exports.Emitter.simpleDispatch (C:\Users\na_gryzlov\AppData\Local\atom\app-1.5.4\resources\app.asar\node_modules\event-kit\lib\emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (C:\Users\na_gryzlov\AppData\Local\atom\app-1.5.4\resources\app.asar\node_modules\event-kit\lib\emitter.js:125:28)
    at Config.module.exports.Config.emitChangeEvent (C:\Users\na_gryzlov\AppData\Local\atom\app-1.5.4\resources\app.asar\src\config.js:816:29)
    at Config.module.exports.Config.setRawValue (C:\Users\na_gryzlov\AppData\Local\atom\app-1.5.4\resources\app.asar\src\config.js:608:19)
    at Config.module.exports.Config.set (C:\Users\na_gryzlov\AppData\Local\atom\app-1.5.4\resources\app.asar\src\config.js:227:14)
    at Config.module.exports.Config.pushAtKeyPath (C:\Users\na_gryzlov\AppData\Local\atom\app-1.5.4\resources\app.asar\src\config.js:361:12)
    at Package.module.exports.Package.disable (C:\Users\na_gryzlov\AppData\Local\atom\app-1.5.4\resources\app.asar\src\package.js:81:26)
    at PackageManager.module.exports.PackageManager.disablePackage (C:\Users\na_gryzlov\AppData\Local\atom\app-1.5.4\resources\app.asar\src\package-manager.js:175:16)
    at HTMLButtonElement.<anonymous> (C:\Users\na_gryzlov\AppData\Local\atom\app-1.5.4\resources\app.asar\node_modules\settings-view\lib\package-card.js:316:27)
    at HTMLButtonElement.jQuery.event.dispatch (C:\Users\na_gryzlov\AppData\Local\atom\app-1.5.4\resources\app.asar\node_modules\jquery\dist\jquery.js:4435:9)
    at HTMLButtonElement.jQuery.event.add.elemData.handle (C:\Users\na_gryzlov\AppData\Local\atom\app-1.5.4\resources\app.asar\node_modules\jquery\dist\jquery.js:4121:28)
```

Looks like whole function body can be removed.
/cc @rgbkrk

### PR DESCRIPTION
**Pull request by nixel2007**
Fix #847 

/cc @rgbkrk

### CODE REVIEW

**Comment by rgbkrk** [comment]
:+1:

**Comment by rgbkrk** [comment]
Should this close section go away entirely now that it's blank?

**Comment by nixel2007** [comment]
@rgbkrk I'm not sure if this function can be omitted (need to check atom api). there are a lot empty functions in this file also.

so i just removed the body.

**Comment by rgbkrk** [comment]
Ok great. Thanks for all the patches and maintenance on script @nixel2007. It wouldn't be the same without you.

**Pull request merged**
