### PR TITLE
Add support for 1C (BSL)

### PR DESCRIPTION
**Pull request by nixel2007**
Hi there!
I'm glad to add support for `1C:Enterprise 8` language http://1c-dn.com/1c_enterprise/what_is_1c_enterprise/

It is a very popular platform with its own DSL for development of business applications in CIS.

You can't run whole app through this runner (`oscript`), but you can run external scripts writen it this language. 

You can find grammar [here](https://atom.io/packages/language-1c-bsl), if you need it

### CODE REVIEW

**Comment by nixel2007** [comment]
Really don't know, why travis-check failed. As you can see, i didn't edit any file related to coffee

**Comment by b1narykid** [comment]
Looks like https://github.com/rgbkrk/atom-script/commit/dbe2740c8e624f44297a6e3079449a96b47a38cd  commit is incompatible with tests (or 'breaks' the code/tests execution)

(Lang=RU) До него тесты на проходили, но после – ни одного теста пройденного (в том числе тесты на PR). Так что проблема в репозитории, а не в Вашем коде.

**Comment by b1narykid** [comment]
Tests are not passing because of this command:
https://travis-ci.org/rgbkrk/atom-script/builds/96838493#L118

**Comment by EvilBeaver** [comment]
+1
1C community needs this functionality!

**Comment by nixel2007** [comment]
Ping?

**Comment by rgbkrk** [comment]
I'll just go ahead and merge this in. I actually think this is not related to @danielbayley's commit. Let me get this fixed up.

**Comment by rgbkrk** [comment]
Thank you for the contribution @nixel2007! Adding you as a maintainer to help review and merge PRs related to 1C or wherever else you want to help. Much appreciated.

**Comment by rgbkrk** [comment]
Nevermind me, I see it too @b1narykid. Thanks for diagnosing it.

/me drinks more :coffee:

**Comment by nixel2007** [comment]
@rgbkrk thank you :)

**Comment by rgbkrk** [comment]
Went ahead and "fixed" it in #708. That could use a better approach to detect if `coffee` even exists on the system to find out the flags.

**Pull request merged**
