### PR TITLE
Add activationCommands

### PR DESCRIPTION
**Pull request by aki77**
[Gyazo](http://gyazo.com/0c19ea9643b8108d9820f14307af11a1)

### CODE REVIEW

**Comment by rgbkrk** [comment]
Is this a before or after picture (can you post both)?

**Comment by aki77** [comment]
## before

[Gyazo](http://gyazo.com/e35356b39b4a4d8e9bc91172c97ab8b1)

## after

[Gyazo](http://gyazo.com/7f0117506e8e32c40ba59a6a50826813)

**Comment by rgbkrk** [comment]
How long does it take to run commands after you add this in? Is our entire activation process hit each time the user runs a new script (after closing the little pane)?

**Comment by aki77** [comment]
> The activate command does a number of things. For one, it is not called automatically when Atom starts up, it is first called when one of the activationCommands as defined in the package.json file are called. In this case, activate is only called the first time the toggle command is called. If nobody ever invokes the menu item or hotkey, this code is never called.
> [3.3 Hacking Atom : Package: Word Count](https://atom.io/docs/latest/hacking-atom-package-word-count)

**Comment by rgbkrk** [comment]
Ok, so this means the tradeoff is between your first run rather than Atom initially booting. I think that's fair.

Thanks for the PR!

**Comment by aki77** [comment]
Tank you!

**Comment by rgbkrk** [comment]
```
$ apm publish minor
Preparing and tagging a new version ✓
Pushing v2.24.0 tag ✓
Publishing script@v2.24.0 ✓
```

**Pull request merged**
