### PR TITLE
Cleanup

### PR DESCRIPTION
**Pull request by mattddowney**
Organized the grammars in the README into a table to make it more clear what types of runs are available. Also alphabetized things in grammars.coffee.

### CODE REVIEW

**Comment by rgbkrk** [comment]
Awesome. Thank you. I'll wait on Travis then :shipit:

**Comment by mattddowney** [comment]
YW. Now to fill in some of the blanks

**Comment by rgbkrk** [comment]
If you're tackling this deeply, we should consider renaming "line based" support. People seem to think that means running line by line, when it's related to some RSpec goodness that I have no idea about.

**Comment by mattddowney** [comment]
I thought it was related to running a single line? IE: <kbd>shift-ctrl-j</kbd>

But you are right, looking at it now, it looks like the only grammars that have that are related to testing frameworks.

Should remove that entire column, you think?

**Comment by rgbkrk** [comment]
> Should remove that entire column, you think?

Yeah.

**Pull request merged**
