### PR TITLE
Add gnuplot scripts

### LINKED ISSUE #744: Add support for gnuplot
How do I add support for a file type?

### PR DESCRIPTION
**Pull request by Luthaf**
Fix #744

### CODE REVIEW

**Comment by nixel2007** [comment]
Does it work OK for you? (workingDirectory thing)

**Comment by Luthaf** [comment]
Yes, completely. Travis failure seems unrelated too.

**Comment by nixel2007** [comment]
May I ask you to add a Readme entry too?

**Comment by Luthaf** [comment]
Done !

**Pull request merged**
