### PR TITLE
Update package.json

### PR DESCRIPTION
**Pull request by nixel2007**
Added myself as a contributor.
@rgbkrk I hope, you don't mind.

### CODE REVIEW

**Comment by rgbkrk** [comment]
This is way overdue! Thank you for all the incredible stewardship of atom script for the past year (?). I appreciate all the merging and shipping.

**Comment by rgbkrk** [comment]
:tada: :tada: :tada:

**Comment by nixel2007** [comment]
Thanks, @rgbkrk :) 
I think, i'm here from december 2015

**Comment by rgbkrk** [comment]
4 months to 🎂  time!

**Pull request merged**
