### PR TITLE
Add Perl 6 support

### PR DESCRIPTION
**Pull request by azawawi**

### CODE REVIEW

**Comment by rgbkrk** [comment]
Looks good. Want to add Perl 6 to the README too?

**Comment by azawawi** [comment]
Done :+1:

**Comment by azawawi** [comment]
Thanks :+1: 

Any ETA on the next release?

**Comment by rgbkrk** [comment]
```
$ apm publish minor
Preparing and tagging a new version ✓
Pushing v2.25.0 tag ✓
Publishing script@v2.25.0 ✓
```

All set, thanks for the extra ping today. I went ahead and merged a PR we were waiting on as well.

:+1:

**Pull request merged**
