### PR TITLE
Improve support for CoffeeScript

### PR DESCRIPTION
**Pull request by danielbayley**
Easily run the latest version [^2] of CoffeeScript. Uses the new `--transpile` feature and _babel-preset-env_ to automatically target the current version Node being run by Atom.

### CODE REVIEW

**Comment by rgbkrk** [comment]
This seems like a good idea. :shipit:

**Comment by danielbayley** [comment]
I just thought, adding _babel-preset-env_ will also open the door for improvements to running JavaScript as a bonus.

@rgbkrk Is the CI supposed to take over an hour though?!

**Comment by rgbkrk** [comment]
That's because of the OS X workers. If we want faster builds we'd have to take them out of the build matrix. As I have little to no time I can invest in this project, it's fine by me if you take them out and go after improving the way JS is run.

**Comment by danielbayley** [comment]
@rgbkrk Why do they take so long?

I've removed them for now. Since I work exclusively on mac, this should be ok temporarily. I should probably reactivate them after I'm done though…

**Comment by rgbkrk** [comment]
Cool, want to check out some of the other open PRs too?

**Comment by danielbayley** [comment]
@rgbkrk I've implemented a bunch of things I wanted to address and closed a bunch of related issues… I'll maybe have a quick look at a few of the PRs that are passing and then cut a release. But then it's back to my todo list!

**Comment by rgbkrk** [comment]
Great thanks @danielbayley!

**Pull request merged**
