### PR TITLE
Adding language support for Sage

### PR DESCRIPTION
**Pull request by Huaraz2**
Sage is a language that allows you to write mathematics in easily.  For more info visit the webiste at http://www.sagemath.org/

### CODE REVIEW

**Comment by Huaraz2** [comment]
Not sure why the selection based commit Is still saying that the Travis is still building, if you click on it says that it has successfully been built.

**Comment by rgbkrk** [comment]
That's pretty odd. I'm a big fan of sage, so hearty :+1: from me. Adding you on as a maintainer as well @Huaraz2.

**Comment by rgbkrk** [comment]
Shipped as 3.2.0, sorry I missed this in 3.1.0. Happy to have you aboard.

**Comment by Huaraz2** [comment]
Thanks @rgbkrk :+1: this is a great package by the way

**Pull request merged**
