### PR TITLE
Added scriptcs support

### PR DESCRIPTION
**Pull request by jchannon**

### CODE REVIEW

**Comment by rgbkrk** [comment]
All boxes checked.

Thank you @jchannon!

**Comment by jchannon** [comment]
No probs! Thank you :)

**Comment by adamralph** [comment]
Nice!

**Comment by rgbkrk** [comment]
:shipit:

```
$ apm publish minor
Preparing and tagging a new version ✓
Pushing v2.23.0 tag ✓
Publishing script@v2.23.0 ✓
```

**Comment by SuperJMN** [comment]
I cannot run scriptcs and yes, scriptcs.exe is in my path under C:\ProgramData\chocolatey\bin;

**Pull request merged**
