### PR TITLE
Rebase atom deprecations

### PR DESCRIPTION
**Pull request by rgbkrk**
This is a follow on to #278, completing more of the deprecations. It involved a rebase, so I'm submitting a new PR with @erran's commits intact.

### CODE REVIEW

**Comment by rgbkrk** [comment]
It's been so long. This is new and slick:

screenshot 2015-02-16 10 56 33

**Comment by rgbkrk** [comment]
Except of course, we didn't catch the error:

screenshot 2015-02-16 10 57 06

Which means we no longer have our nifty dialog with an Issue link. :cry:

**Comment by rgbkrk** [comment]
The trickiest one is going to be working with a new way of displaying our little viewer.

```
atom.workspaceView is no longer available. In most cases you will not need the view. See the Workspace docs for alternatives: https://atom.io/docs/api/latest/Workspace. If you do need the view, please use atom.views.getView(atom.workspace), which returns an HTMLElement.
```

Hopping on a plane, hope I get to reinvigorate this soon.

**Comment by rgbkrk** [comment]
I'm going to be busy at Strata for a few, feel free to add on if you get time @erran or just merge as is. Everything is working but we're still not living in the future with Atom here.

**Comment by erran** [comment]
> I'm going to be busy at Strata for a few, feel free to add on if you get time @erran or just merge as is. Everything is working but we're still not living in the future with Atom here.

I've personally being using good ol' `vim` a lot recently. I've been in and out of Atom. I'll probably have some time this weekend to hack away on some of my own projects in which case I'll definitely dedicate some time to atom-script.

**Comment by rgbkrk** [comment]
Ok if we put this much in at the very least? Should cut down on reports quite a bit.

**Comment by erran** [comment]
Yeah, these changes look good.

**Comment by rgbkrk** [comment]
I was about to release this too then I realized you had a flow for how you were populating the changelog.

**Comment by rgbkrk** [comment]
Shipped.

```
Preparing and tagging a new version ✓
Pushing v2.17.0 tag ✓
Publishing script@v2.17.0 ✓
```

**Pull request merged**
