### PR TITLE
Add support for HTML

### LINKED ISSUE #724: Add support for HTML
Please add support for displaying HTML in the console.

It could just render it as plain text, respecting only new lines and `<br>` tags. It could reasonably ignore all javascript tags, style sheets, and any other markup.

### PR DESCRIPTION
**Pull request by lgeiger**
Closes #724

### CODE REVIEW

**Comment by nixel2007** [comment]
Oh God. Now we can "run" html!

**Comment by rgbkrk** [comment]
And so it is done.

**Comment by rgbkrk** [comment]
Thank you @lgeiger, this has been the bane of my existence.

**Comment by lgeiger** [comment]
👍 I'll ship a new version.

**Comment by andyrichardson** [comment]
Why stop at HTML? I'd love to see atom script play mp3 files.

Jokes aside, nice work guys :+1:

**Pull request merged**
