### PR TITLE
Don't save unless buffer is modified

### PR DESCRIPTION
**Pull request by plerup**
Important when using makefiles

### CODE REVIEW

**Comment by nixel2007** [comment]
Thanks for the PR, @plerup!

**Comment by nixel2007** [comment]
@plerup please, could you edit your code to pass the tests?
https://travis-ci.org/rgbkrk/atom-script/jobs/140867063

**Comment by plerup** [comment]
Sorry, don't understand what the error is and how it relates to the change

**Comment by nixel2007** [comment]
@plerup looks like this module compiles before any editor (file) is opened.
I think something like `if editor?.isModified()` may help

**Comment by nixel2007** [comment]
Shipped in 3.8.0 (and 3.8.1) :ship:

**Pull request merged**
