### PR TITLE
Porting ScriptView to use MessagePanelView

### PR DESCRIPTION
**Pull request by ncreep**
A pull request for #631.
This allows resizing and minimization of the output panel. 

Unlike what's mentioned in the issue, this commit directly overwrites `ScriptView` with the new functionality. Also, I think I figured out the conditional scrolling bit mentioned in the issue, so it's included as well (see [here](https://github.com/ncreep/atom-script/blob/42c77e733f0eabef242feec1c7c79be9b593ba98/lib/script-view.coffee#L125)).

### CODE REVIEW

**Comment by woopstar** [comment]
Tested this. Does not work for me.

I'm only able to resize it smaller, not bigger.

**Comment by ncreep** [comment]
On my machine, what I see is that the panel cannot be resized beyond the height of the content in it.
Is it actually ever needed to make the panel longer than its content?

**Comment by Huaraz2** [comment]
@ncreep I have tested this on my machine and I cannot resize or close the screen at all now. I have copied all of the files that you have changed correctly as far as I can tell. See pic below for the problem I get.
image

**Comment by ncreep2** [comment]
@Huaraz2, I'm not seeing the panel at all in the screenshot you attached.

**Comment by Huaraz2** [comment]
@ncreep2 everything that you can see is the output from the script package, the output panel has covered the R code I had in the test.R file that I have opened.

**Comment by ncreep2** [comment]
Strange, there should be buttons in the right corner of the panel. I'm not sure, what could be wrong with it, are you sure that you applied all of my changes?

It would be best if you could just checkout [my code](https://github.com/ncreep/atom-script/tree/be3a20529ca95b526421a6365595cacbf4401238) and open it in development mode in Atom (as in the instructions in the [README](https://github.com/rgbkrk/atom-script#development)).

**Comment by Huaraz2** [comment]
As far as I was aware I did. Will try again later though.
>are you sure that you applied all of my changes?

**Comment by Huaraz2** [comment]
Have tried again and have got it working now. seems as though the dependencies did not install despite me doing apm install in the package directory like i am supposed to do.  @ncreep this is a brilliant PR :+1: I really like the fact that you can minimise the output menu. Is there a way to have multiple output windows?

**Comment by woopstar** [comment]
Tested this. LGTM.

**Comment by Huaraz2** [comment]
:+1: 
>Tested this. LGTM.

**Comment by ncreep** [comment]
@Huaraz2, if by "multiple output" you mean "multiple panels", I don't think that using the new panel affects the ability to implement multiple output. Though I didn't investigate this issue to any depth.

**Comment by Huaraz2** [comment]
@ncreep, yes I did mean this
>by "multiple output" you mean "multiple panels" 

I haven't looked into doing this at all I only wondered if it was possible to do. Maybe look at doing something similar to what the `terminal-plus` package does but again I am not sure how we could go about doing this.

**Comment by rgbkrk** [comment]
Cool, thanks all! Adding you on as a maintainer @ncreep.

**Comment by rgbkrk** [comment]
Shipped it.

```
$ apm publish minor
Preparing and tagging a new version ✓
Pushing v3.1.0 tag ✓
Publishing script@v3.1.0 ✓
```

**Comment by ncreep** [comment]
Great, glad to see it merged.

**Pull request merged**
