### PR TITLE
Rust cwd

### PR DESCRIPTION
**Pull request by mirek**
Allow accessing files relative to script location.

### CODE REVIEW

**Comment by hastebrot** [comment]
This maybe needs special support for Windows.

**Comment by rgbkrk** [comment]
Yeah, we'll need something for Windows here. Any suggestions?

**Comment by hastebrot** [comment]
I tried this, but couldn't make it work :confused:.

~~~cs
Rust:
  "File Based":
    command: "cmd"
    args: (context) -> ['/C cd "' + context.dirname + '" && rustc "' + context.filepath + '" -o "%TEMP%\\rs.exe" && "%TEMP%\\rs.exe"']
~~~

**Comment by rgbkrk** [comment]
Any updates on Windows handling @mirek?

**Comment by mirek** [comment]
I'm in Brazil, I don't even know how to get windows here.

**Comment by rgbkrk** [comment]
Awww I didn't mean for you to close it, just that I want you to case it off for Linux, Windows, and possibly Darwin (OS X). Just adding @hastebrot's suggestion could work for now.

**Pull request closed without merging**
