### PR TITLE
Fixed MIPS execution

### PR DESCRIPTION
**Pull request by W3D3**
Fixed the execution of MIPS scripts using spim.
Also added small HelloWorld example for testing.

### CODE REVIEW

**Comment by nixel2007** [comment]
👍

**Comment by nixel2007** [comment]
:ship: 3.11.0

**Comment by Austinthemighty** [comment]
how do i set up spim for atom, every time i try to run it i keep getting this

> Unable to run
>
>spim
>
>Did you start Atom from the command line?
>
>  atom .
>
>Is it in your PATH?
>
>PATH: /opt/local/bin:/opt/local/sbin:/Library/Frameworks/Python.framework/Versions/2.7/bin:/Library/Frameworks/Python.framework/Versions/3.6/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Applications/VMware Fusion.app/Contents/Public:/opt/X11/bin:/Library/Frameworks/Mono.framework/Versions/Current/Commands:/usr/local/CrossPack-AVR/bin:/usr/local/bin

**Comment by W3D3** [comment]
I mean the error message says it: You don't have spim in your path. Either you add the installation directory of spim to your $PATH variable or move it to /usr/local/bin for example.
If you install spim using homebrew, it already should be in your path, if not try 'brew link spim'

**Comment by Austinthemighty** [comment]
ok thanks, I installed it using the packing installer, didn't know there was a homebrew option as well, once I did that it worked, now the only problem is that it keeps printing out 

> Loaded: /usr/local/Cellar/spim/9.1.19/share/exceptions.s

and nothing else

**Comment by W3D3** [comment]
It could just be the case that your code simply prints nothing?

Try running [hello.asm](https://github.com/rgbkrk/atom-script/blob/master/examples/hello.asm) which should print 'Hello world!'.

**Comment by Austinthemighty** [comment]
Hello world worked, but for some reason, mine does not even though it prints out in mars, also my script does ask for a user input which i think is causing the problem
<script src="https://gist.github.com/Austinthemighty/f514278f0c959a078dbdabe7a6fb1470.js"></script>

**Comment by Austinthemighty** [comment]
Also on atom when i run it, i shows the hourglass and nothing happens.

**Comment by W3D3** [comment]
Yeah but i think that's a general problem with this extention, it simply doesn't allow user input.

**Comment by Austinthemighty** [comment]
well, that sucks, as all the programs that I am having to write for school requires a users input.

**Pull request merged**
