### PR TITLE
First atempt to edit profiles

### LINKED ISSUE #787: Add ability to edit saved profile
Now you can only save and run profile. No "edit" command is presented.

/cc @Stormherz

### PR DESCRIPTION
**Pull request by nixel2007**
/cc @rgbkrk @Stormherz 
So... Sometimes it doesn't crash the Atom :)

In theory the passing options to script-options-view is done.
Need to get it back and save in profile.

_But..._
In 1.7 i have some `Cannot read property 'hide' of undefined` or `Cannot read property 'isVisible' of undefined` and so on...

This should fix #787

### CODE REVIEW

**Comment by rgbkrk** [comment]
> In 1.7 i have some Cannot read property 'hide' of undefined or Cannot read property 'isVisible' of undefined and so on...

Yuck.

**Comment by rgbkrk** [comment]
I'm going to have to come back to this. I don't have bandwidth for it today.

**Comment by nixel2007** [comment]
@rgbkrk ping?

**Comment by rgbkrk** [comment]
How about we merge it, carry forward, and see what could happen?

**Comment by nixel2007** [comment]
It isn't done. You can't really edit and save the profile. Only open an edit window with filled fields.

**Comment by rgbkrk** [comment]
This needs a rebase if we want to carry it forward since it's in JS. Should we close this one for now?

**Comment by nixel2007** [comment]
Yeah, I think you can close it. 
I effort to vsc development for last year, my interest to Atom is mostly gone :(

**Comment by rgbkrk** [comment]
Hey that's ok, thanks for all the maintenance work you've done. I don't use this package _at all_ so I'm happy when others hack on it and help people. :smile:

**Pull request closed without merging**
